// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioplnmonwupvucvxkxiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcGxubW9ud3VwdnVjdnhreGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTcxMTUsImV4cCI6MjA2NjYzMzExNX0.VIjzruJQ-Ls2gS3AHW6p8JCQH1KDqhvpPuMs_7JS6Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});